### PR TITLE
Add weekly sync meeting notes 2020-11-09

### PR DESCRIPTION
**Pull request by vmx**

### CODE REVIEW

**Review by mvdan — APPROVED** [review]
You could also add the decision that naming the new Go package go-multicodec is fine for now, given that others like js-multicodec are the same and they'd all need to be fixed in the future anyway (if we rename the table).

**Comment by vmx** [comment]
@mvdan You should've write access to this PR. Feel free to just add this as another commit to this PR :)

**Review by rvagg — APPROVED** [review]

**Comment by vmx** [comment]
@mvdan I've added a not about "go-multicodec".

**Comment by mvdan** [comment]
Ah, thank you. I saw your comment, thought "I'll do that in a bit", then forgot :)

**Pull request merged**
